struct: NaCl.xyz
struct-name: NaCl
supercell: 2x2x2
displacement: 0.01
fmax: 0.001
thermal: True
temp-start: 0
temp-end: 1000
temp-step: 10
band: True
dos: True
minimize: True
minimize-kwargs:
  filter_func: null

arch: mace_mp
write-full: True
plot-to-file: True
calc-kwargs:
  model: small
device: cpu
